"""Agent state definition using Pydantic V2 for strict schema validation."""

from typing import Annotated, Literal, TypedDict

from pydantic import BaseModel, Field


class ResearchPlan(BaseModel):
    """Structured research plan generated by the Planner node."""

    query: str = Field(..., description="Original user query")
    sub_queries: list[str] = Field(
        default_factory=list,
        description="Decomposed sub-queries for targeted research (should include site: and filetype: filters for technical queries)",
    )
    search_terms: list[str] = Field(
        default_factory=list,
        description="Enhanced search terms with site: and filetype: modifiers (e.g., 'AI architecture site:arxiv.org filetype:pdf')",
    )
    domains: list[str] | None = Field(
        default=None,
        description="Optional domain filters for technical queries (e.g., ['arxiv.org', 'github.com'])",
    )
    required_domains: list[str] = Field(
        default_factory=list,
        description="Required domains for academic/technical queries (e.g., ['arxiv.org', 'scholar.google.com'] for academic research)",
    )


class SearchResult(BaseModel):
    """Individual search result from Tavily API."""

    title: str = Field(..., description="Result title")
    url: str = Field(..., description="Source URL")
    content: str = Field(..., description="Result content/snippet")
    score: float = Field(
        default=0.0,
        description="Relevance score (0-1)",
        ge=0.0,
        le=1.0,
    )


class ResearchResults(BaseModel):
    """Aggregated research results from Researcher node."""

    results: list[SearchResult] = Field(
        default_factory=list,
        description="List of search results",
    )
    total_count: int = Field(
        default=0,
        description="Total number of results retrieved",
        ge=0,
    )


class Critique(BaseModel):
    """Critique evaluation from Critic node."""

    quality_score: float = Field(
        ...,
        description="Overall quality score (0-1)",
        ge=0.0,
        le=1.0,
    )
    is_sufficient: bool = Field(
        ...,
        description="Whether quality meets threshold to proceed",
    )
    issues: list[str] = Field(
        default_factory=list,
        description="List of identified issues (staleness, bias, gaps)",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Recommendations for improvement if insufficient",
    )


class FinalReport(BaseModel):
    """Final synthesized report from Writer node."""

    content: str = Field(..., description="Report content")
    sources: list[str] = Field(
        default_factory=list,
        description="List of source URLs cited",
    )
    confidence: float = Field(
        default=0.0,
        description="Confidence score (0-1)",
        ge=0.0,
        le=1.0,
    )


class AgentState(TypedDict):
    """LangGraph state definition using TypedDict for state machine."""

    # Input
    user_query: str

    # Planner Output
    research_plan: Annotated[ResearchPlan | None, "Research plan from planner"]

    # Researcher Output
    research_results: Annotated[ResearchResults | None, "Aggregated search results"]

    # Critic Output
    critique: Annotated[Critique | None, "Quality critique and evaluation"]

    # Writer Output
    final_report: Annotated[FinalReport | None, "Final synthesized report"]

    # Control Flow
    current_node: Annotated[
        Literal["planner", "researcher", "critic", "writer", "end"],
        "Current node in execution",
    ]
    iteration_count: Annotated[int, "Number of research-critic cycles completed"]
    error: Annotated[str | None, "Error message if execution failed"]
