"""Agent state definition using Pydantic V2 for strict schema validation."""

from typing import Annotated, Literal, TypedDict

from pydantic import BaseModel, Field

from domain.models import Claim, Evidence, Source


class ResearchPlan(BaseModel):
    """Structured research plan generated by the Planner node."""

    query: str = Field(..., description="Original user query")
    sub_queries: list[str] = Field(
        default_factory=list,
        description="Decomposed sub-queries for targeted research (should include site: and filetype: filters for technical queries)",
    )
    search_terms: list[str] = Field(
        default_factory=list,
        description="Enhanced search terms with site: and filetype: modifiers (e.g., 'AI architecture site:arxiv.org filetype:pdf')",
    )
    domains: list[str] | None = Field(
        default=None,
        description="Optional domain filters for technical queries (e.g., ['arxiv.org', 'github.com'])",
    )
    required_domains: list[str] = Field(
        default_factory=list,
        description="Required domains for academic/technical queries (e.g., ['arxiv.org', 'scholar.google.com'] for academic research)",
    )


class SearchResult(BaseModel):
    """Individual search result from Tavily API."""

    title: str = Field(..., description="Result title")
    url: str = Field(..., description="Source URL")
    content: str = Field(..., description="Result content/snippet")
    score: float = Field(
        default=0.0,
        description="Relevance score (0-1)",
        ge=0.0,
        le=1.0,
    )


class ResearchResults(BaseModel):
    """Aggregated research results from Researcher node."""

    results: list[SearchResult] = Field(
        default_factory=list,
        description="List of search results",
    )
    total_count: int = Field(
        default=0,
        description="Total number of results retrieved",
        ge=0,
    )


class Critique(BaseModel):
    """Evidence-grounded critique evaluation from Critic node."""

    quality_score: float = Field(
        ...,
        description="Overall quality score (0-1) based on validated evidence",
        ge=0.0,
        le=1.0,
    )
    is_sufficient: bool = Field(
        ...,
        description="Whether evidence quality meets threshold to proceed",
    )
    coverage: str = Field(
        default="",
        description="Assessment of whether evidence addresses the research question",
    )
    source_quality: str = Field(
        default="",
        description="Assessment of source quality for key evidence",
    )
    source_diversity: str = Field(
        default="",
        description="Assessment of source independence and diversity",
    )
    temporal_alignment: str = Field(
        default="",
        description="Whether evidence matches the requested time period",
    )
    potential_conflicts: list[str] = Field(
        default_factory=list,
        description="Potential contradictions between evidence items",
    )
    unsupported_areas: list[str] = Field(
        default_factory=list,
        description="Important aspects of the question not covered by evidence",
    )
    issues: list[str] = Field(
        default_factory=list,
        description="List of identified issues",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Recommendations for improvement if insufficient",
    )


class FinalReport(BaseModel):
    """Final synthesized report from Writer node."""

    content: str = Field(..., description="Report content with [E#] evidence refs")
    sources: list[str] = Field(
        default_factory=list,
        description="Source URLs backed by cited validated evidence",
    )
    confidence: float = Field(
        default=0.0,
        description="Evidence confidence (numeric mapping of level, not probability)",
        ge=0.0,
        le=1.0,
    )
    confidence_level: str = Field(
        default="medium",
        description="Evidence confidence: high, medium, or low",
    )
    confidence_reasoning: str = Field(
        default="",
        description="Explanation of evidence confidence assessment",
    )
    answer_confidence_level: str = Field(
        default="medium",
        description="How strongly the core answer is supported",
    )
    answer_confidence_reasoning: str = Field(
        default="",
        description="Explanation of answer confidence",
    )
    research_completeness_level: str = Field(
        default="medium",
        description="How comprehensively the question was investigated",
    )
    research_completeness_reasoning: str = Field(
        default="",
        description="Explanation of research completeness",
    )
    evidence_ids_used: list[str] = Field(
        default_factory=list,
        description="Evidence display IDs cited in report",
    )
    report_metrics: dict = Field(
        default_factory=dict,
        description="Observability metrics for report generation",
    )


class AgentState(TypedDict):
    """LangGraph state definition using TypedDict for state machine."""

    # Input
    user_query: str

    # Query routing (Phase 2B.5+)
    query_classification: Annotated[
        dict | None, "Query complexity classification and research budget"
    ]
    fast_path_metrics: Annotated[
        dict | None, "Fast path execution observability"
    ]
    escalate_to_standard: Annotated[
        bool, "Whether to escalate from fast path to full pipeline"
    ]
    escalated_from_fast_path: Annotated[
        bool, "Whether this run escalated from fast path"
    ]
    escalation_reason: Annotated[
        str | None, "Reason for escalation to standard pipeline"
    ]
    material_claims: Annotated[
        list[Claim] | None, "Claims material to answering the research question"
    ]
    claim_evidence_relations: Annotated[
        list | None, "Claim-evidence relationship links"
    ]
    verification_results: Annotated[
        list | None, "Cross-source verification results per material claim"
    ]
    verification_metrics: Annotated[
        dict | None, "Claim verification observability metrics"
    ]
    knowledge_state: Annotated[
        dict | None, "Derived knowledge state snapshot (Phase 2D)"
    ]
    decision_frame: Annotated[
        dict | None, "Structured decision frame (Phase 3A)"
    ]
    decision_frame_metrics: Annotated[
        dict | None, "Decision framing observability metrics"
    ]
    option_evaluation: Annotated[
        dict | None, "Evidence-grounded option evaluation (Phase 3B)"
    ]
    option_evaluation_metrics: Annotated[
        dict | None, "Option evaluation observability metrics"
    ]
    cost_metrics: Annotated[
        dict | None, "Cost and latency observability metrics"
    ]
    research_sufficient: Annotated[
        bool, "Whether authoritative evidence is sufficient to stop researching"
    ]

    # Research run tracking
    research_run_id: Annotated[int | None, "Database ID of the current research run"]
    is_run_persisted: Annotated[bool, "Whether research_run_id refers to a DB row"]
    normalized_sources: Annotated[
        list[Source] | None, "Normalized and persisted source records"
    ]
    validated_evidence: Annotated[
        list[Evidence] | None, "Validated evidence extracted from sources"
    ]
    evidence_metrics: Annotated[
        dict | None, "Evidence extraction observability metrics"
    ]
    validated_claims: Annotated[
        list[Claim] | None, "Validated atomic claims extracted from evidence"
    ]
    claim_metrics: Annotated[
        dict | None, "Claim extraction observability metrics"
    ]
    source_dedup_metrics: Annotated[
        dict | None, "Source canonicalization deduplication metrics"
    ]
    report_metrics: Annotated[
        dict | None, "Report generation observability metrics"
    ]

    # Planner Output
    research_plan: Annotated[ResearchPlan | None, "Research plan from planner"]

    # Researcher Output
    research_results: Annotated[ResearchResults | None, "Aggregated search results"]

    # Critic Output
    critique: Annotated[Critique | None, "Quality critique and evaluation"]

    # Writer Output
    final_report: Annotated[FinalReport | None, "Final synthesized report"]

    # Control Flow
    current_node: Annotated[
        Literal[
            "router",
            "fast_path",
            "planner",
            "researcher",
            "evidence_extractor",
            "claim_extractor",
            "claim_verifier",
            "critic",
            "decision_framer",
            "knowledge_state",
            "option_evaluator",
            "writer",
            "end",
        ],
        "Current node in execution",
    ]
    iteration_count: Annotated[int, "Number of research-critic cycles completed"]
    error: Annotated[str | None, "Error message if execution failed"]
